### ISSUE TITLE
Trinket / IDLE / Mu Compatibility

### ISSUE THREAD

**Issue by tracygardner** [raspberrypilearning/where-is-the-space-station#18]
https://github.com/RaspberryPiFoundation/python-curriculum/issues/86

Can we make changes so that the same code works in Trinket and offline?

**Comment by martinohanlon** [comment]
Resolved issues, made all images gifs and cast lat & lon to floats. 
New screenshots for modified code.
Created new trinkets for the starter and complete projects and updated all the resources.

**Comment by martinohanlon** [comment]
It needs a test then I will push to master.

**Comment by martinohanlon** [comment]
Resolved with PR https://github.com/raspberrypilearning/where-is-the-space-station/pull/20
