### ISSUE TITLE
projects site feedback  (Jul 2019)

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/where-is-the-space-station#22]
URL: /en/projects/where-is-the-space-station/complete .decode ('utf-8') is needed to parse the data as there must be some characters in it that Python doesn't know what to do with

**Comment by tracygardner** [comment]
Not clear which Python editor was giving an error. The mentioned approach doesn't work in Trinket which is why it isn't used, this project isn't currently written for other editors. However, the current code in the project does work in Thonny.
