### ISSUE TITLE
Error in code, producing wrong result.

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/where-is-the-space-station#63]
The instructions say, "Now let’s get the first pass-over time from the result." The code following uses an index of 1. However, [0] is actually the first result and  [1] is the second result.

https://projects.raspberrypi.org/en/projects/where-is-the-space-station/6

**Comment by tracygardner** [comment]
Maybe there was once a reason why it was like this but I can't see one now! Updated.
